### ISSUE TITLE
list Patches related to given BUG

### ISSUE THREAD

**Issue by berx** [MarisElsins/getMOSPatch#12]
With an URL like https://support.oracle.com/epmos/faces/BugMatrix?id=<BUG_ID> a list of all Related Patches to this Bug can be retrieved (among other information).
If this list is displayed it can be parsed, or directly used to download all related patches.

**Comment by MarisElsins** [comment]
I'm not finding time/priority to implement this.
If someone develops the change I'll merge it into the main code.
