### ISSUE TITLE
Continually being prompted for username/password

### ISSUE THREAD

**Issue by dbpiv** [MarisElsins/getMOSPatch#14]
When using getMOSPatch I am being prompted for credentials even though I have supplied them.

java -jar getMOSPatch.jar patch=28542658 platform=226P stagedir=~/Downloads/MOSPatch download=all
Enter your MOS username: me@email.com
Enter your MOS password: 
Enter your MOS username: me@email.com
Enter your MOS password: 
Enter your MOS username: me@email.com 
Enter your MOS password: 

dbpiv_tbMBP:~ dbpiv$ java -jar getMOSPatch.jar MOSUser='me@email.com' MOSPass='SuperSecretPassword' patch=28542658 platform=226P stagedir=~/Downloads/MOSPatch download=all
Enter your MOS username: me@email.com
Enter your MOS password: 
Enter your MOS username: me@email.com
Enter your MOS password: 
Enter your MOS username: me@email.com
Enter your MOS password: 

I believe this is related to the the latest Mojave upgrade.

javac -version
javac 1.8.0_172

**Comment by dbpiv** [comment]
DOH!  My apologies.  I forgot that I updated my password for oracle.com.  You were correct to assume it was a password issue.  Thanks for taking the time to follow up.

dp

**Comment by MarisElsins** [comment]
No Problem :) Better this than something wrong with the tool :D
