### ISSUE TITLE
getMOSPatch.jar is not giving option to skip the patch from the list

### ISSUE THREAD

**Issue by pythianmarti** [MarisElsins/getMOSPatch#15]
While downloading patch 28700057 NLS language (FRC) version for R12.2, utility didnt let to skip downloading the patch as R12.1 has FRC version and forcing to choose option for this release. Can you review and embed option to skip the patch if required release patch is not available. Thanks.

**Comment by MarisElsins** [comment]
You can use "none" as a valid selector in the newest V2.4
