### ISSUE TITLE
ERROR: Unparsable inputs. Try Again.

### ISSUE THREAD

**Issue by ket000** [MarisElsins/getMOSPatch#17]
Getting this error now. I am assuming Oracle may have changed the way it sends the Platform list. 

Platforms and languages need to be reset.
Obtaining the list of platforms and languages:
-
Enter Comma separated platforms to list:
 ERROR: Unparsable inputs. Try Again.
Enter Comma separated platforms to list:233P
 ERROR: Unparsable inputs. Try Again.
Enter Comma separated platforms to list:

**Comment by MarisElsins** [comment]
Yes, something was changed by Oracle.
I'll be looking into it, meanwhile, you can use the old and obsolete shell script with similar functionality - https://github.com/MarisElsins/TOOLS/blob/master/Shell/getMOSPatch.sh
It still works.

**Comment by ket000** [comment]
Thanks. It seems that platform list is no longer there. I may change the
source code to disable validation for now.

**Comment by ket000** [comment]
I tried commenting out code that does validation, but it still fails 

            // check the inputs as many times as necessary
            //while (!CheckInputs(listplatforms, platforms)) {
            //    System.out.println(" ERROR: Unparsable inputs. Try Again.");
           //     listplatforms = console.readLine("Enter Comma separated platforms to list:");
            //}

Here is the output.
Enter Comma separated platforms to list: 233P

We're going to download patches for the following Platforms/Languages:
 233P - null

Processing patch 30861472 for null and applying regexp .* to the filenames:
https://updates.oracle.com/Orion/SimpleSearch/process_form?search_type=patch&patch_number=30861472&plat_lang=233P
 No files available

Processing patch 31035002 for null and applying regexp .* to the filenames:
https://updates.oracle.com/Orion/SimpleSearch/process_form?search_type=patch&patch_number=31035002&plat_lang=233P
 No files available

There's Nothing to download!

**Comment by NateWerner** [comment]
FYI, I was able to resolve this by using the URL  https://updates.oracle.com/Orion/Services/download to complete the Authentication/SSO step.

**Comment by MarisElsins** [comment]
Thanks for the hints:
Resolved in the latest uploaded version v2.1 in 86cad7e0dbf06afd074dc8c2208e9a5e67a2dd72
