### ISSUE TITLE
getMosPatch does not work anymore...

### ISSUE THREAD

**Issue by Pafke01** [MarisElsins/getMOSPatch#19]
Maris,

It seems Oracle has changed something and it is impossible to use the download site anymore.

java -jar getMOSPatch.jar MOSUser=mymailadress  MOSPass=<hidden> reset=yes
Platforms and languages need to be reset.
Obtaining the list of platforms and languages:
-
Enter Comma separated platforms to list: Linux
 ERROR: Unparsable inputs. Try Again.
Enter Comma separated platforms to list:226P

I will try to debug with your shell script because I am unable to program in Java.
I heard from customers that even downloading with OEM causes problems.

Regards,
Paulfrans Musolf

**Comment by Pafke01** [comment]
Please ignore my post....

**Comment by MarisElsins** [comment]
Download the newest version of getMOSPatch. It should work as this issue was addressed.
