### ISSUE TITLE
Empty platform list on first run

### ISSUE THREAD

**Issue by dsmule-git** [MarisElsins/getMOSPatch#22]
When I run this for the first time with the reset=yes option I get no list of platforms to choose from.

$java -jar getMOSPatch.jar reset=yes debug=yes                                                                                                                                                      Platforms and languages need to be reset.
Obtaining the list of platforms and languages:                                                                                                                                                                                       -
Enter Comma separated platforms to list: ^C

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

**Comment by MarisElsins** [comment]
Hi,

I couldn't reproduce it, the output when no patch number is specified is this:
```
$ java -jar getMOSPatch.jar reset=yes debug=yes

No patch numbers are specified.
```

If I do specify a patch number, I get:
```
$ java -jar getMOSPatch.jar reset=yes debug=yes patch=6880880
Enter your MOS username: ***
Enter your MOS password: 
Platforms and languages need to be reset.
Obtaining the list of platforms and languages:
537P - Acme Packet 1100
529P - Acme Packet 3820
540P - Acme Packet 3900
530P - Acme Packet 4500
538P - Acme Packet 4600
534P - Acme Packet 6100
...
lots of lines
...
43L - Vietnamese (VN)
999L - Worldwide Spanish (ESW)

Enter Comma separated platforms to list: ^C
```

Could you:
1. Make sure you're using the latest available version of the utility (download it again!)
1. provide me with an exact copy of the command and it's outputs that reproduces the problem.
1. provide me with the outputs of `ls -la | grep getMOS` from the directory you're running the utility in.

Maris

**Comment by Psharm89** [comment]
Even i am facing this issue, earlier i was able download the file but now i am facing` No files available`. 

With `.getMOSPatch.cfg` file 
```
-
We're going to download patches for the following Platforms/Languages:
 226P - Linux x86-64

Processing patch 6880880 for Linux x86-64 and applying regexp .*1120.* to the filenames:
 No files available

There's nothing to download!

```
and after removing the .cfg file

```
java -jar getMOSPatch.jar reset=yes debug=yes patch=6880880
Platforms and languages need to be reset.
Obtaining the list of platforms and languages:
-
Enter Comma separated platforms to list:
```
I am not  getting the list of Platforms and languages.

**Comment by MarisElsins** [comment]
Acknowledged.
Something has changed in the user authentication flow on MOS side, and it causes the logon and the subsequent http calls to MOS fail.
I'm looking into it.

**Comment by MarisElsins** [comment]
I just uploaded a new version that should bypass this problem.
Please, let me know if it works for you!

**Comment by Psharm89** [comment]
Thanks but i am getting the below error.

```
java  -jar getMOSPatch.jar MOSUser=abc@test.com patch=6880880 regexp=.*121.* download=all
Enter your MOS password:
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder
	at getMOSPatch.getFinalURL(getMOSPatch.java:149)
	at getMOSPatch.getFinalURL(getMOSPatch.java:160)
	at getMOSPatch.downloadFile(getMOSPatch.java:187)
	at getMOSPatch.downloadString(getMOSPatch.java:261)
	at getMOSPatch.downloadString(getMOSPatch.java:257)
	at getMOSPatch.main(getMOSPatch.java:528)
Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more
```

**Comment by MarisElsins** [comment]
You tested too early :), try again I uploaded a new one 5 minutes ago.

**Comment by MarisElsins** [comment]
I'll assume this issue fixed. Please open a new one if something's still not right.

**Comment by Psharm89** [comment]
Yes, Thanks you so much :)
