### ISSUE TITLE
missing #1 when returning patch list

### ISSUE THREAD

**Issue by dxh137** [MarisElsins/getMOSPatch#24]
Hi there,
thanks for sharing the code! very nice. 
[patch download.docx](https://github.com/MarisElsins/getMOSPatch/files/5424134/patch.download.docx)
when I run with a patch having multiple releases, it shown like:
Processing patch 29997959 for Linux x86-64 and applying regexp .* to the filenames:                                                                                                                               1 - p29997959_189000OJVMRU_Generic.zip
 2 - p29997959_12201191015OJVMRU_Generic.zip
 3 - p29997959_190000_Generic.zip
 4 - p29997959_188000OJVMRU_Generic.zip
 5 - p29997959_122010_Generic.zip
 6 - p29997959_180000_Generic.zip
 Enter Comma separated files to download ("all" or "none" can be used too):

1 did not shown on the screen, but when I copied here, it shown up

**Comment by dxh137** [comment]
[patch download.docx](https://github.com/MarisElsins/getMOSPatch/files/5424145/patch.download.docx)

**Comment by dxh137** [comment]
try to download patch 30128197 for 226P - Linux x86-64. got: There's nothing to download! but the patch exist on Oracle Support. 

Patch 30128197: OJVM PATCH SET UPDATE 12.1.0.2.191015 for Linux x86-64.

**Comment by dxh137** [comment]
there patch doesn't require password

**Comment by MarisElsins** [comment]
Yes, 

I know about this issue, the 1 ends up at the end of the previous line due to the spinning progress indicator.
And for the other thing - the 30128197, not sure. I downloaded the patch just finer:
```
$ java -jar getMOSPatch.jar patch=30128197 platform=226P
Enter your MOS username: ***
Enter your MOS password:
-
We're going to download patches for the following Platforms/Languages:
 226P - Platform 226P

Processing patch 30128197 for Platform 226P and applying regexp .* to the filenames:
 1 - p30128197_121020_Linux-x86-64.zip
 Enter Comma separated files to download ("all" or "none" can be used too): 1

Downloading all selected files:
 Downloading p30128197_121020_Linux-x86-64.zip: 99MB at average speed of 8542KB/s - DONE!
```
