### ISSUE TITLE
I can not download patch with "Merged Translation"

### ISSUE THREAD

**Issue by eLuko** [MarisElsins/getMOSPatch#25]
Hello,

getMOSPatch does't download patches with "Merged Translation". Sometimes Oracle Support can not fully translate patch example: p30721310_R12.OWF.B_R12_hu_p.zip. This kind of patch have additional page with warring and you have pick Yes or No. That why getMOSPatch can't download this patch.

Regards,
Luko

**Comment by MarisElsins** [comment]
Very old issue, closing it. Sorry I had no time to address it.
