### ISSUE TITLE
Downloads broken today

### ISSUE THREAD

**Issue by ripleymj** [MarisElsins/getMOSPatch#26]
I wish I had more detail to offer at this point, but I just wanted to give you a heads-up that myself and a colleague are suddenly seeing getMOSPatch return "o files available. There's nothing to download!" without even prompting for MOS credentials. Hopefully I can dig into this a bit more later, but wanted to put the issue out here in case anyone has ideas or wanted to know that they're not alone in seeing problems today

**Comment by MarisElsins** [comment]
Hi,
Thanks for the feedback.
I just tested it on patch 6880880 (Opatch) and it worked fine. Make sure the patch is not password protected or has an Extended support contract requirement by logging on to MOS and trying to download it from there.
I've seen this happen only when download is not possible via MOS either.
Maris
