### ISSUE TITLE
Resume Downloads

### ISSUE THREAD

**Issue by Rendanic** [MarisElsins/getMOSPatch#3]
I try some downloads and when I stop the process and restart the getMOSPatch the whole download starts at the beginning, which is bad for big files. Is it possible to resume an aborted download with an additional parameter?

**Comment by MarisElsins** [comment]
It's not currently possible to resume a download, but I'll keep this issue open to take a look at it when I have time. Thanks!

**Comment by MarisElsins** [comment]
Very old issue, closing it. Sorry I had no time to address it.
