### ISSUE TITLE
Patch list display issue

### ISSUE THREAD

**Issue by sniperkitten** [MarisElsins/getMOSPatch#30]
Hi

I've noticed that in my terminal '1' is not displayed for the list of patches. Surprisingly when I copied it into a notepad++, I was able to see it. But I've noticed that there's no newline after "filenames:". I guess that's why the first line is cut off in the beginning in my terminal. I can't paste a screenshot here unfortunately, but that's how it looks for me:

Processing patch 33660731 for Linux x86-64 and applying regexp .* to the filenames:                                                                                                                                                                          - p33660731_12213210929_Generic.zip
 2 - p33660731_12214210930_Generic.zip
 3 - p33660731_14110210930_Generic.zip
 Enter Comma separated files to download ("all" or "none" can be used too): 2

Please take a look at it

Thank you

**Comment by MarisElsins** [comment]
I couldn't reproduce it. it must be some kind of terminal incompatibility issue. The utility deletes and replaces a character to draw the rotating progress indicator "/", and it looks like the list might have been printed at an "unfortunate moment". I hope this is not too annoying and you can still  use it as is!

**Comment by sniperkitten** [comment]
Yes, it's usable. Thank you for taking a look at it!
