### ISSUE TITLE
Tool does not find all referenced patches for platforms specified

### ISSUE THREAD

**Issue by rbrackma** [MarisElsins/getMOSPatch#7]
Really a great tool !

This might be due to how Oracle classifies things, I still open an issue...

When trying to download JDK1.7u141 for Win32 & Win64, only one of two patches is found by the tool.

Do you have any idea ?
Thanks
Roland

**How to reproduce**
1. Connect to https://support.oracle.com/epmos/faces/DocContentDisplay?_afrLoop=550217370350059&id=1412103.2&_afrWindowMode=0&_adf.ctrl-state=dli07hh5b_543
2. spot the ID when you hover over the JDK7 link, do not click on it https://support.oracle.com/epmos/faces/PatchResultsNDetails?patchId=13079846
3. enter that id 13079846 from URL here 

// platform 912P = Win32 and 208P = Win64
java -jar getMOSPatch.jar patch=13079846 platform=912P,208P reset=yes download=all stagedir="%TEMP%"

**Outcome of getMOSPatch.jar run** 
We're going to download patches for the following Platforms/Languages:
 208P - Microsoft Windows Itanium (64-bit)
 912P - Microsoft Windows (32-bit)

Processing patch 13079846 for Microsoft Windows Itanium (64-bit) and applying regexp .* to the filenames:
 No files available

Processing patch 13079846 for Microsoft Windows (32-bit) and applying regexp .* to the filenames:
 1 - p13079846_17000_WINNT.zip
 Enter Comma separated files to download: all
 All files will be downloadad because download=all was specified.

**Comment by MarisElsins** [comment]
Hi, 

Thanks for the feedback!

I think you're using the wrong platform code for the 64b windows. The platform codes are:

   * 912P - Microsoft Windows (32-bit)
   * 208P - Microsoft Windows Itanium (64-bit)
   * 233P - Microsoft Windows x64 (64-bit)

I think you need ```912P,233P```

Maris

**Comment by rbrackma** [comment]
Hey,
thanks for the answer... and ouach.
That was it...
Roland
