### ISSUE TITLE
Feature request : find a patch ID that is "hidden" in a commulative patch ID

### ISSUE THREAD

**Issue by rbrackma** [MarisElsins/getMOSPatch#8]
Would it be possilbe to track all the patches that encorporate a patch A? 
This is extremely painful via the Oracle support interface (thus maybe impossible via tool), you see the screenshot.

I would like to feed getMOSPatch with 18057437 and get a choice as seen in the screenshot (maybe allowing to retrieve the description)...

![image](https://cloud.githubusercontent.com/assets/6652644/25739301/9d61e430-3181-11e7-8861-8652b8d883d2.png)

**Comment by MarisElsins** [comment]
I see what you mean, but I don't think it's realistic. There's too much inconsistency in how oracle describes their patches.

**Comment by rbrackma** [comment]
OK fair. You are in a good position to judge.
